#!/bin/sh
set -e

# --- Konfiguracja GOST OS Live Build ---
# Używamy trybu "debian", aby uniknąć dziedziczenia z Ubuntu.
# Dystrybucja: Debian 13 "Trixie" (testing)

lb config noauto \
    --mode "debian" \
    --distribution "trixie" \
    --parent-distribution "trixie" \
    --archive-areas "main contrib non-free non-free-firmware" \
    \
    # --- Architektura i jądro ---
    --architectures "amd64" \
    --linux-packages "linux-image" \
    \
    # --- Konfiguracja systemu Live ---
    --initramfs "live-boot" \
    \
    # --- Obraz ISO ---
    --binary-images "iso-hybrid" \
    --bootloader "grub-pc" \
    --iso-application "GOST OS Debian 13 Trixie" \
    --iso-publisher "GOSTOS CI/CD" \
    --iso-volume "GOSTOS_TRIXIE" \
    \
    # --- Komponenty dodatkowe ---
    --memtest "memtest86+" \
    --debian-installer "live" \
    --debian-installer-gui "true" \
    \
    "${@}"

echo "[GOST-OS] Konfiguracja auto/config zakończona pomyślnie."
